[project]
name = "anthuria-project"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.0.2",
    "pandas>=3.0.1",
    "pdfplumber>=0.11.9",
    "requests>=2.32.5",
]
